# Generated by Django 5.0.7 on 2024-08-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_types',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.ManyToManyField(blank=True, to='user_manager.usertype'),
        ),
    ]
